// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutingApi.Data;

#nullable disable

namespace ScoutingApi.Migrations
{
    [DbContext(typeof(ScoutingDbContext))]
    [Migration("20250918193654_AddUsuarioScopeToJogadoresClubes")]
    partial class AddUsuarioScopeToJogadoresClubes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutingApi.Models.Avaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text")
                        .HasColumnName("comentarios_gerais");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_avaliacao");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("LocalAvaliacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("local_avaliacao");

                    b.Property<decimal?>("NotaFinal")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("nota_final");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("avaliacoes", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.AvaliacaoFisica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AvaliacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("avaliacao_id");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resultado");

                    b.Property<string>("Teste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("teste");

                    b.Property<string>("TipoTeste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_teste");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("avaliacao_fisica", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.AvaliacaoTaticaComportamental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AvaliacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("avaliacao_id");

                    b.Property<short?>("Competitividade")
                        .HasColumnType("smallint")
                        .HasColumnName("competitividade");

                    b.Property<short?>("DisciplinaTatica")
                        .HasColumnType("smallint")
                        .HasColumnName("disciplina_tatica");

                    b.Property<short?>("InteligenciaEmocional")
                        .HasColumnType("smallint")
                        .HasColumnName("inteligencia_emocional");

                    b.Property<short?>("LeituraJogo")
                        .HasColumnType("smallint")
                        .HasColumnName("leitura_jogo");

                    b.Property<short?>("Posicionamento")
                        .HasColumnType("smallint")
                        .HasColumnName("posicionamento");

                    b.Property<short?>("TomadaDecisao")
                        .HasColumnType("smallint")
                        .HasColumnName("tomada_decisao");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId")
                        .IsUnique();

                    b.ToTable("avaliacao_tatica_comportamental", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.AvaliacaoTecnicaQuantitativa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Acertos")
                        .HasColumnType("integer")
                        .HasColumnName("acertos");

                    b.Property<long>("AvaliacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("avaliacao_id");

                    b.Property<string>("Exercicio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("exercicio");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("TipoExercicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_exercicio");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("avaliacao_tecnica_quantitativa", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pais");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("clubes", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.HistoricoClube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer")
                        .HasColumnName("clube_id");

                    b.Property<DateOnly?>("DataEntrada")
                        .HasColumnType("date")
                        .HasColumnName("data_entrada");

                    b.Property<DateOnly?>("DataSaida")
                        .HasColumnType("date")
                        .HasColumnName("data_saida");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("JogadorId");

                    b.ToTable("historico_clubes", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Altura")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("altura");

                    b.Property<int?>("ClubeAtualId")
                        .HasColumnType("integer")
                        .HasColumnName("clube_atual_id");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<string>("PeDominante")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pe_dominante");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("posicao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClubeAtualId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("jogadores", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.JogadorFavorito", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("jogadores_favoritos", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Lembrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("concluido");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "CreatedAt");

                    b.ToTable("lembretes", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Lesao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataOcorrencia")
                        .HasColumnType("date")
                        .HasColumnName("data_ocorrencia");

                    b.Property<DateOnly?>("DataRecuperacao")
                        .HasColumnType("date")
                        .HasColumnName("data_recuperacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("LocalCorpo")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("local_corpo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<string>("TipoLesao")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipo_lesao");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("lesoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_lesoes_local", "local_corpo IN ('JL','TB','CM','OM','CT','OT')");

                            t.HasCheckConstraint("CK_lesoes_tipo", "tipo_lesao IN ('M','L','O','C','N')");
                        });
                });

            modelBuilder.Entity("ScoutingApi.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AvaliacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("avaliacao_id");

                    b.Property<string>("CaminhoPdf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminho_pdf");

                    b.Property<DateTime?>("DataGeracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_geracao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("JogadorId");

                    b.ToTable("relatorios", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuarios_perfil", "perfil IN ('A','O','T')");
                        });
                });

            modelBuilder.Entity("ScoutingApi.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoVideo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminho_video");

                    b.Property<DateTime?>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("Marcacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("marcacoes");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Avaliacao", b =>
                {
                    b.HasOne("ScoutingApi.Models.Usuario", "Avaliador")
                        .WithMany()
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliador");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.AvaliacaoFisica", b =>
                {
                    b.HasOne("ScoutingApi.Models.Avaliacao", "Avaliacao")
                        .WithMany("Fisicas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("ScoutingApi.Models.AvaliacaoTaticaComportamental", b =>
                {
                    b.HasOne("ScoutingApi.Models.Avaliacao", "Avaliacao")
                        .WithOne("TaticaComportamental")
                        .HasForeignKey("ScoutingApi.Models.AvaliacaoTaticaComportamental", "AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("ScoutingApi.Models.AvaliacaoTecnicaQuantitativa", b =>
                {
                    b.HasOne("ScoutingApi.Models.Avaliacao", "Avaliacao")
                        .WithMany("TecnicasQuantitativas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("ScoutingApi.Models.Clube", b =>
                {
                    b.HasOne("ScoutingApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutingApi.Models.HistoricoClube", b =>
                {
                    b.HasOne("ScoutingApi.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("HistoricoClubes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Jogador", b =>
                {
                    b.HasOne("ScoutingApi.Models.Clube", "ClubeAtual")
                        .WithMany()
                        .HasForeignKey("ClubeAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScoutingApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubeAtual");
                });

            modelBuilder.Entity("ScoutingApi.Models.JogadorFavorito", b =>
                {
                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("FavoritadoPor")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ScoutingApi.Models.Lembrete", b =>
                {
                    b.HasOne("ScoutingApi.Models.Usuario", "Usuario")
                        .WithMany("Lembretes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ScoutingApi.Models.Lesao", b =>
                {
                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Lesoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Relatorio", b =>
                {
                    b.HasOne("ScoutingApi.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Relatorios")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Video", b =>
                {
                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Videos")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Avaliacao", b =>
                {
                    b.Navigation("Fisicas");

                    b.Navigation("TaticaComportamental");

                    b.Navigation("TecnicasQuantitativas");
                });

            modelBuilder.Entity("ScoutingApi.Models.Jogador", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("FavoritadoPor");

                    b.Navigation("HistoricoClubes");

                    b.Navigation("Lesoes");

                    b.Navigation("Relatorios");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ScoutingApi.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Lembretes");
                });
#pragma warning restore 612, 618
        }
    }
}
