// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutingApi.Data;

#nullable disable

namespace ScoutingApi.Migrations
{
    [DbContext(typeof(ScoutingDbContext))]
    [Migration("20250826025015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutingApi.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliador_id");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comentarios");

                    b.Property<int?>("ControleBola")
                        .HasColumnType("integer")
                        .HasColumnName("controle_bola");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int?>("Disciplina")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina");

                    b.Property<int?>("Drible")
                        .HasColumnType("integer")
                        .HasColumnName("drible");

                    b.Property<int?>("Finalizacao")
                        .HasColumnType("integer")
                        .HasColumnName("finalizacao");

                    b.Property<int?>("Forca")
                        .HasColumnType("integer")
                        .HasColumnName("forca");

                    b.Property<int?>("InteligenciaEmocional")
                        .HasColumnType("integer")
                        .HasColumnName("inteligencia_emocional");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<int?>("LeituraJogo")
                        .HasColumnType("integer")
                        .HasColumnName("leitura_jogo");

                    b.Property<int?>("Lideranca")
                        .HasColumnType("integer")
                        .HasColumnName("lideranca");

                    b.Property<int?>("Passe")
                        .HasColumnType("integer")
                        .HasColumnName("passe");

                    b.Property<int?>("Posicionamento")
                        .HasColumnType("integer")
                        .HasColumnName("posicionamento");

                    b.Property<int?>("Proatividade")
                        .HasColumnType("integer")
                        .HasColumnName("proatividade");

                    b.Property<int?>("Resistencia")
                        .HasColumnType("integer")
                        .HasColumnName("resistencia");

                    b.Property<int?>("TomadaDecisao")
                        .HasColumnType("integer")
                        .HasColumnName("tomada_decisao");

                    b.Property<int?>("Velocidade")
                        .HasColumnType("integer")
                        .HasColumnName("velocidade");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("avaliacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_avaliacoes_score_fis", "velocidade BETWEEN 0 AND 10 AND resistencia BETWEEN 0 AND 10 AND forca BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_avaliacoes_score_psc", "disciplina BETWEEN 0 AND 10 AND lideranca BETWEEN 0 AND 10 AND proatividade BETWEEN 0 AND 10 AND inteligencia_emocional BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_avaliacoes_score_tat", "posicionamento BETWEEN 0 AND 10 AND leitura_jogo BETWEEN 0 AND 10 AND tomada_decisao BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_avaliacoes_score_tec", "controle_bola BETWEEN 0 AND 10 AND passe BETWEEN 0 AND 10 AND finalizacao BETWEEN 0 AND 10 AND drible BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("ScoutingApi.Models.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pais");

                    b.HasKey("Id");

                    b.ToTable("clubes", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.HistoricoClube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer")
                        .HasColumnName("clube_id");

                    b.Property<DateOnly?>("DataEntrada")
                        .HasColumnType("date")
                        .HasColumnName("data_entrada");

                    b.Property<DateOnly?>("DataSaida")
                        .HasColumnType("date")
                        .HasColumnName("data_saida");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("JogadorId");

                    b.ToTable("historico_clubes", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Altura")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("altura");

                    b.Property<int?>("ClubeAtualId")
                        .HasColumnType("integer")
                        .HasColumnName("clube_atual_id");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<string>("PeDominante")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pe_dominante");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("posicao");

                    b.HasKey("Id");

                    b.HasIndex("ClubeAtualId");

                    b.ToTable("jogadores", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Lesao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataOcorrencia")
                        .HasColumnType("date")
                        .HasColumnName("data_ocorrencia");

                    b.Property<DateOnly?>("DataRecuperacao")
                        .HasColumnType("date")
                        .HasColumnName("data_recuperacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("LocalCorpo")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("local_corpo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<string>("TipoLesao")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipo_lesao");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("lesoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_lesoes_local", "local_corpo IN ('JL','TB','CM','OM','CT','OT')");

                            t.HasCheckConstraint("CK_lesoes_tipo", "tipo_lesao IN ('M','L','O','C','N')");
                        });
                });

            modelBuilder.Entity("ScoutingApi.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacao_id");

                    b.Property<string>("CaminhoPdf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminho_pdf");

                    b.Property<DateTime?>("DataGeracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_geracao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("JogadorId");

                    b.ToTable("relatorios", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuarios_perfil", "perfil IN ('A','O','T')");
                        });
                });

            modelBuilder.Entity("ScoutingApi.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoVideo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminho_video");

                    b.Property<DateTime?>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogador_id");

                    b.Property<string>("Marcacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("marcacoes");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("ScoutingApi.Models.Avaliacao", b =>
                {
                    b.HasOne("ScoutingApi.Models.Usuario", "Avaliador")
                        .WithMany()
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliador");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.HistoricoClube", b =>
                {
                    b.HasOne("ScoutingApi.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("HistoricoClubes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Jogador", b =>
                {
                    b.HasOne("ScoutingApi.Models.Clube", "ClubeAtual")
                        .WithMany()
                        .HasForeignKey("ClubeAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClubeAtual");
                });

            modelBuilder.Entity("ScoutingApi.Models.Lesao", b =>
                {
                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Lesoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Relatorio", b =>
                {
                    b.HasOne("ScoutingApi.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Relatorios")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Video", b =>
                {
                    b.HasOne("ScoutingApi.Models.Jogador", "Jogador")
                        .WithMany("Videos")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("ScoutingApi.Models.Jogador", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("HistoricoClubes");

                    b.Navigation("Lesoes");

                    b.Navigation("Relatorios");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
